[build]
  command = "npm run deploy-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --production=false --prefer-offline --no-audit"
  NODE_OPTIONS = "--max_old_space_size=3072"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true 